// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEdDIqQWusj7JEUhsUnuD8gLCatcZbYjo',
    appId: '1:761597986669:web:481b3fe2c6d1c16d253c64',
    messagingSenderId: '761597986669',
    projectId: 'notes-t',
    authDomain: 'notes-t-d2bca.firebaseapp.com',
    storageBucket: 'notes-t.appspot.com',
    measurementId: 'G-BR8E367JHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALzbv-Jy6W-XeGe2tQoyAx3gH5FsM5smE',
    appId: '1:761597986669:android:7d0615d3e8bdb691253c64',
    messagingSenderId: '761597986669',
    projectId: 'notes-t',
    storageBucket: 'notes-t.appspot.com',
  );
}
